---
name: CustomAnvil
version: 1.0.0
api: [3.0.0, 3.1.0, 4.0.0]
main: Anvil\Main
author: DaRealAqua
depend:
- EconomyAPI
- FormAPI
description: This plugin is usefull for SkyBlock,Factions,HCF servers!
...
